# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200317_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pod_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_podcategory', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name_podcategory'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pod_category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='podcategory', to='shop.Pod_Category', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
