# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200319_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_category',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='products_pd', to='shop.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
