# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_recomend'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recomend',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемые'),
        ),
    ]
