# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_recomend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glav',
            field=models.CharField(choices=[('smartphon', 'Smartphon'), ('naushniki', 'Naushniki'), ('noutbooki', 'Noutbooki')], default=12, max_length=7, verbose_name='на главной'),
            preserve_default=False,
        ),
    ]
