# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-21 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_glav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='glav',
        ),
    ]
