# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_glav'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_prodaj',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
    ]
