# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_hit_prodaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_tovar',
            field=models.BooleanField(default=False, verbose_name='Новый новар'),
        ),
    ]
