# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_gallery',
            field=models.ManyToManyField(blank=True, to='shop.Gallery', verbose_name='фото товара'),
        ),
    ]
