# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-27 12:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_comments_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_contact', models.CharField(max_length=200, verbose_name='контакт')),
                ('body_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='текст')),
                ('adress_one_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='первый адрес')),
                ('adress_toe_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='второй адрес')),
                ('tel', models.CharField(max_length=200, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакт',
            },
        ),
    ]
