# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='pod_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pod_category',
        ),
        migrations.AddField(
            model_name='category',
            name='pod_categoty',
            field=models.ManyToManyField(to='shop.Pod_Category', verbose_name='подкатегории'),
        ),
        migrations.AddField(
            model_name='pod_category',
            name='product',
            field=models.ManyToManyField(to='shop.Product', verbose_name='товар'),
        ),
    ]
