# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200331_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=12, max_length=200, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
