# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_category',
            name='one',
            field=models.BooleanField(default=False, verbose_name='первая колонка'),
        ),
    ]
