# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_pod_category_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod_category',
            name='one',
        ),
        migrations.AddField(
            model_name='pod_category',
            name='image',
            field=models.ImageField(blank=True, upload_to='podcategory/%Y/%m/%d/', verbose_name='Изображение подкатегории'),
        ),
    ]
