# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-08 16:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200405_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostiopl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagolovok', models.CharField(db_index=True, max_length=200, verbose_name='заголовок')),
                ('predtekst', models.CharField(db_index=True, max_length=200, verbose_name='предтекст')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='первый адрес')),
            ],
            options={
                'verbose_name': 'Доставка и оплата',
                'verbose_name_plural': 'Доставка и оплата',
                'ordering': ['zagolovok'],
            },
        ),
    ]
