# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_dostiopl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_carusel', models.CharField(db_index=True, max_length=200, verbose_name='заголовок')),
            ],
        ),
    ]
