# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-31 16:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_carusel_tovar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carusel',
        ),
        migrations.AddField(
            model_name='contact',
            name='web',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='email'),
        ),
    ]
