# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200610_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_gallery',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара2'),
        ),
    ]
