# Generated by Django 3.0.7 on 2020-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_prodaj2',
            field=models.BooleanField(default=False, verbose_name='Хит продаж2'),
        ),
    ]
