# Generated by Django 3.0.7 on 2020-07-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_hit_prodaj2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hit_prodaj2',
            field=models.BooleanField(default=False, verbose_name='Хит продаж2 (270*40)'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_com', models.CharField(max_length=100)),
                ('body_com', models.TextField(max_length=250)),
                ('rate', models.IntegerField(blank=True)),
                ('status_com', models.CharField(choices=[('New', 'Yeni'), ('True', 'Evet'), ('False', 'Hayir')], default='New', max_length=10)),
                ('ip_com', models.CharField(blank=True, max_length=20)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
