# Generated by Django 3.0.7 on 2020-07-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20200707_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status_com',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product_com',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.Product'),
            preserve_default=False,
        ),
    ]
