# Generated by Django 3.0.8 on 2020-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20200711_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.BooleanField(default=False, verbose_name='акция'),
        ),
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.CharField(blank=True, max_length=80, verbose_name='бренд'),
        ),
    ]
