# Generated by Django 3.0.8 on 2020-07-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_brend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brend',
        ),
    ]
