# Generated by Django 3.0.8 on 2020-07-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_product_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, to='shop.Brend', verbose_name='бренд'),
            preserve_default=False,
        ),
    ]
